### ISSUE TITLE
Can't declare variables on Oakland demo compiler

### ISSUE THREAD

**Issue by ElrohirGT** [nxz7/OLC2_Proyecto1_202200007#1]
Hi! Wanted to try out your project but when I tried to use the compiler to declare a variable and print it out to console it outputs the following:

![image](https://github.com/user-attachments/assets/495d5a40-0ed5-44a9-9267-791af9b399dd)

How can I declare a variable in Oakland?

**Comment by nxz7** [comment]
Hi there! You got it right—declaring a variable in Oakland works that way. However, the error lies at the end of your code on the last line; it must end with a ;.

I tried it, and it seems to work fine. (see the image below)
![Output](https://github.com/user-attachments/assets/d6f77042-278c-4f5d-b610-84b0ce19e36c)

[func.txt](https://github.com/user-attachments/files/18132513/func.txt)
[loops.txt](https://github.com/user-attachments/files/18132514/loops.txt)

I'm attaching two .txt test files, loops and functions, in case you're curious about the project and want to check it out!! (Since they are not .oak files, you'll need to copy the text and then paste it)

**Comment by ElrohirGT** [comment]
Gotcha, thank you! It's been a long time since I last programmed in anything Java inspired.

Have a nice day!
